# Use trusty for better performance (and avoiding mysql/postgres/solr gone issues on precise and container infra)
dist: trusty
sudo: required

language: php

services:
  - mysql

# Mysql isn't installed on trusty (only client is), so we need to specifically install it
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    # For functional and acceptance tests
    - COMPOSE_FILE="doc/docker/base-dev.yml:doc/docker/selenium.yml"
    # In order to specify extra flags like ignoring platform reqs, using only stable packages and so on.
    - COMPOSER_FLAGS=""
    - EZPLATFORM_REPO="https://github.com/ezsystems/ezplatform.git"

matrix:
  fast_finish: true
  include:
# 7.3
    - name: "PHP 7.3 Unit tests"
      php: 7.3
      env: TEST_CONFIG="phpunit.xml"
    - name: "PHP 7.3 REST Integration Tests"
      php: 7.3
      env: REST_TEST_CONFIG="phpunit-integration-rest.xml" TEST_CMD="./bin/.travis/run_rest_tests.sh" APP_ENV=behat PHP_IMAGE=ezsystems/php:7.3-v1-node PHP_IMAGE_DEV=ezsystems/php:7.3-v1-dev APP_DEBUG=1 SF_CMD="ez:behat:create-language 'pol-PL' 'Polish (polski)'"
    - name: "Code Style Check"
      php: 7.3
      env: CHECK_CS=1

# test only master, stable branches and pull requests
branches:
  only:
    - master
    - /^\d.\d+$/

# setup requirements for running unit/integration/behat tests
before_install:
  # Disable memory_limit for composer
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Prepare system
  - if [ "$REST_TEST_CONFIG" != "" ] ; then ./.travis/prepare_ezplatform.sh ; fi
  # Execute Symfony command if specified
  - if [ "$SF_CMD" != "" ] ; then cd "$HOME/build/ezplatform"; docker-compose exec --user www-data app sh -c "bin/console $SF_CMD" ; fi
  # Detecting timezone issues by testing on random timezone
  - TEST_TIMEZONES=("America/New_York" "Asia/Calcutta" "UTC")
  - TEST_TIMEZONE=${TEST_TIMEZONES["`shuf -i 0-2 -n 1`"]}

install:
  - if [ "$CHECK_CS" == "1" -o "$TEST_CONFIG" != "" ]; then travis_retry composer install --prefer-dist --no-interaction --no-suggest ; fi

# execute phpunit or behat as the script command
script:
  - if [ "$TEST_CONFIG" != "" ] ; then php -d date.timezone=$TEST_TIMEZONE -d memory_limit=-1 vendor/bin/phpunit -c $TEST_CONFIG ; fi
  - if [ "$REST_TEST_CONFIG" != "" ] ; then cd "$HOME/build/ezplatform"; docker-compose exec app sh -c "$TEST_CMD"  ; fi
  - if [ "$CHECK_CS" == "1" ] ; then ./vendor/bin/php-cs-fixer fix -v --dry-run --show-progress=estimating ; fi

notifications:
  slack:
    rooms:
      - secure: EesyExipldfURHELpH76Dp31/CePOvkJAjg9sw1OF/FdNtuAiOr9LzU3xmVDrZRJwVgjtyfHS/RqwrkS883ohZVo4p38uA+XsMDjWJ/KzGzQGpqFivPH3hv3MUjaHjASokF9ChbBhwp0RY/bCiRSaKEAuHmVJnbFU7C81Pd0Fr7ObSc0GrhMX728VFX38I8RLzaYG656nrUszHGkER8Mz8y0QYdSbxQhfiN67d2+U1e/sZaY44nP4MDPKkqTkIDLb8e/wgGT97Lj05KHTXps7UVsJLQeQ14dSmAQKo6QMAz+LEz+/Rd3JN9B50D4pbU/gM0L1JbNcsb4D2asXWP3ZHF0EaZQ0uv1n5pOgw1DJEdTa6VsbM+r4Wbq/PE+IdZoIBZTyojWKD/tbzUapd6kX2fOq0DyZaUCvXNEIAOPbwfI/TstLtbU7eWBwzTsdW5V5PTcRqxjpCtzxMeNlarNWDzWP97nkgf7xErOkiMGE4g8wyaKqFG4EBDilQNzmUCqRKdgNUXmxxD7oxU0c6t8qnrp7mpud+jm3u0VoQKzNCDOLTZyA6k3Vd/lGwm3VKMfadi0x/Ssy5JE0mNcA9b4Vrt2fn/iAHMLf/qop3m49evaY9ytyiEmux/mFpFL3LiCrmGac/rqDL4h0eCjeQFuKfJJwu7RKuvHhsXX7yrOvaU=
    on_success: change
    on_failure: always
    on_pull_requests: false

# reduce depth (history) of git checkout
git:
  depth: 30
